name: CI workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: Shibil
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print name
        run: echo $NAME
