name: CI workflow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: Shibil
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: print name
        run: echo "Name is: $NAME"
