name: CI workflow
on:
  push:
jobs:
  runs-on: ubuntu-latest
  env:
    name: Shibil
  steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: print name
      run: echo "Name is: $name"
